# Generated by Django 4.1.7 on 2023-02-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='date_born',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
